--**asset pivoting
SELECT ASSET_NAME,EQUIPMENT,M_DATE,MONTHLY_OPR_HRS
FROM TB_ASSET_OPH
UNPIVOT (MONTHLY_OPR_HRS
FOR		M_DATE IN (
				JAN012014 AS '01-JAN-14',
				FEB012014 AS '01-FEB-14',
				MAR012014 AS '01-MAR-14',
				APR012014 AS '01-APR-14',
				MAY012014 AS '01-MAY-14',
				JUN012014 AS '01-JUN-14',
				JUL012014 AS '01-JUL-14',
				AUG012014 AS '01-AUG-14',
				SEP012014 AS '01-SEP-14',
				OCT012014 AS '01-OCT-14',
				NOV012014 AS '01-NOV-14',
				DEC012014 AS '01-DEC-14',
				JAN012015 AS '01-JAN-15',
				FEB012015 AS '01-FEB-15',
				MAR012015 AS '01-MAR-15',
				APR012015 AS '01-APR-15',
				MAY012015 AS '01-MAY-15',
				JUN012015 AS '01-JUN-15',
				JUL012015 AS '01-JUL-15',
				AUG012015 AS '01-AUG-15',
				SEP012015 AS '01-SEP-15',
				OCT012015 AS '01-OCT-15',
				NOV012015 AS '01-NOV-15',
				DEC012015 AS '01-DEC-15',
				JAN012016 AS '01-JAN-16',
				FEB012016 AS '01-FEB-16',
				MAR012016 AS '01-MAR-16',
				APR012016 AS '01-APR-16',
				MAY012016 AS '01-MAY-16',
				JUN012016 AS '01-JUN-16',
				JUL012016 AS '01-JUL-16',
				AUG012016 AS '01-AUG-16',
				SEP012016 AS '01-SEP-16',
				OCT012016 AS '01-OCT-16',
				NOV012016 AS '01-NOV-16',
				DEC012016 AS '01-DEC-16'
				));


Hi Tom -
https://asktom.oracle.com/pls/asktom/f?p=100:11:::::P11_QUESTION_ID:185012348071


First time writer and big fan of yours.  This thread caught my interest, and I wanted to suggest an 
approach similar to one mentioned above that seems to have significantly better performance than 
the initial suggestion (not so dependent on interval length).

Not enough room to post the entire script here, but I've cut out the more significant pieces and 
pasted below.  See embedded comments for further explanation, but the basic idea is that there's no 
need to iterate through each day in the interval if you only want to count the business days.  For 
an interval of 1 year, my function shaves a couple of orders of magnitude off the performance of 
the initial solution.  I've verified that the calculation is equivalent, but left off those details 
for brevity's sake as well.  I also have a "SQL Built-Ins"-only expression version of my function, 
but the performance was virtually identical to that of the stored user-defined function, so again 
left off for space reasons.

/*
|| holiday_table holds the dates to be excluded from the interval calculation
*/
CREATE TABLE holiday_table
 ( holiday_date DATE )
/*
|| Inserted 12/31/02, 1/1/03, 2/17/03, 5/26/03, 7/4/03, 9/1/03, 11/27/03,
|| 11/28/03, 12/24/03, 12/25/03, 12/31/03, and 1/1/04 into holiday_table
*/
CREATE TABLE test_interval
 ( start_date  DATE,
   end_date    DATE
 )
/*
|| Inserted 500 rows into test_interval, with dates ranging from 12/02 into 5/04
|| Tested intervals ranged from 1 day apart to beyond 1 year apart
*/
/*
|| The PL/SQL implementation of the business day logic
*/
CREATE OR REPLACE FUNCTION busdays_between
 ( p_start_dt DATE,
   p_end_dt   DATE )
RETURN NUMBER
IS
   cln_start_dt DATE        := TRUNC( p_start_dt );
   cln_end_dt   DATE        := TRUNC( p_end_dt );
   first_dt     DATE;
   last_dt      DATE;
   orientation  PLS_INTEGER := 1;
   first_dowk   PLS_INTEGER;
   count_first  PLS_INTEGER := 1;
   last_dowk    PLS_INTEGER;
   wks_btwn     PLS_INTEGER;
   sat_adjst    PLS_INTEGER := 0;
   count_hdays  PLS_INTEGER := 0;
   return_value NUMBER;
BEGIN
   IF cln_start_dt <= cln_end_dt
   THEN
      first_dt := cln_start_dt;
      last_dt := cln_end_dt;
   ELSE
      first_dt := cln_end_dt;
      last_dt := cln_start_dt;
      orientation := -1;
   END IF;
   SELECT COUNT( * )
     INTO count_hdays
     FROM holiday_table
    WHERE holiday_date BETWEEN first_dt
                           AND last_dt;
   first_dowk := TO_NUMBER( TO_CHAR( first_dt, 'D' ) );
   last_dowk := TO_NUMBER( TO_CHAR( last_dt, 'D' ) );
   wks_btwn := TRUNC( ( last_dt - first_dt ) / 7 );
   IF first_dowk > last_dowk
   THEN
      wks_btwn := wks_btwn + 1;
   END IF;
   IF first_dowk = 7
   THEN
      sat_adjst := 1;
      count_first := 0;
   ELSIF first_dowk = 1
   THEN
      count_first := 0;
   ELSE
      NULL;
   END IF;
   IF last_dowk = 7
   THEN
      sat_adjst := sat_adjst - 1;
   END IF;
   return_value := ( ( wks_btwn * 5 ) +
                     ( last_dowk - first_dowk + count_first ) +
                     sat_adjst - count_hdays
                   ) * orientation;
   RETURN return_value;
END; /* busdays_between */
/*


--############
With Asset AS (
SELECT 
SQL_142.prv_value ASSET_NAME,
O.OBJ_CODE Equipment,
O.OBJ_VARIABLE3 MF_Hrs_of_Ops,
OBJ_VARIABLE4 SA_Hrs_of_Ops,
OBJ_VARIABLE5 SU_Hrs_of_Ops,

CASE LENGTH(OBJ_VARIABLE4)
  WHEN 4 THEN 'ALL'
  WHEN 1    THEN 'MF'
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE 'MFSS'
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS OP_DAY,

CASE LENGTH(OBJ_VARIABLE3)
  WHEN 4 THEN 24
  WHEN 1    THEN 0
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE Round(to_number(to_char(TO_DATE( substr(OBJ_VARIABLE3,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE3,1,4),'HH24MI')))*24,1)
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS MF_TIME,

CASE LENGTH(OBJ_VARIABLE4)
  WHEN 4 THEN 24
  WHEN 1    THEN 0
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE Round(to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI')))*24,1)
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS SAT_TIME,

CASE LENGTH(OBJ_VARIABLE5)
  WHEN 4 THEN 24
  WHEN 1    THEN 0
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE Round(to_number(to_char(TO_DATE( substr(OBJ_VARIABLE5,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE5,1,4),'HH24MI')))*24,1)
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS SUN_TIME

--OBJ_VARIABLE6 WK_Hrs_of_Ops
FROM r5objects o  , r5propertyvalues SQL_142

WHERE o.obj_obrtype ='A' AND O.OBJ_STATUS <> 'EO' AND O.OBJ_STATUS <> 'RET' AND O.OBJ_STATUS = 'I' AND SQL_142.prv_value IS NOT NULL AND
obj_code||'#'||obj_org=SQL_142.prv_code(+) AND (SQL_142.prv_rentity(+) = 'OBJ') AND (SQL_142.prv_property(+)='ASSETNAM')
and O.OBJ_CLASS = 'MRI'
ORDER BY SQL_142.prv_value),
--##start year calculation here##--

Jan16 AS
  (
     SELECT 
            TO_DATE('01-JAN-16') AS InstallDate,
            TO_DATE('31-JAN-16') AS CompleteDate

       FROM dual
  )

--SELECT ASSET_NAME, Equipment, OP_Day ,MF_TIME, SAT_TIME, SUN_TIME, Jan16 
--FROM Asset, Jan16

SELECT ASSET_NAME, Equipment, OP_DAY, MF_TIME, SAT_TIME, SUN_TIME,
 
  CASE OP_DAY
    WHEN 'MF' THEN 
      ((TRUNC(CompleteDate) - TRUNC(InstallDate) ) +1 - 
      ((((TRUNC(CompleteDate,'D'))-(TRUNC(InstallDate,'D')))/7)*2) -
      (CASE WHEN TO_CHAR(InstallDate,'DY','nls_date_language=english')='SUN' THEN 1 ELSE 0 END) -
      (CASE WHEN TO_CHAR(CompleteDate,'DY','nls_date_language=english')='SAT' THEN 1 ELSE 0 END))*MF_TIME 
    WHEN 'MFSS' THEN 
      ((TRUNC(CompleteDate) - TRUNC(InstallDate) ) +1 - 
      ((((TRUNC(CompleteDate,'D'))-(TRUNC(InstallDate,'D')))/7)*2) -
      (CASE WHEN TO_CHAR(InstallDate,'DY','nls_date_language=english')='SUN' THEN 1 ELSE 0 END) -
      (CASE WHEN TO_CHAR(CompleteDate,'DY','nls_date_language=english')='SAT' THEN 1 ELSE 0 END))*MF_TIME 
      +
      ((((TRUNC(CompleteDate,'D'))-(TRUNC(InstallDate,'D')))/7)*2 +
      (CASE WHEN TO_CHAR(InstallDate,'DY','nls_date_language=english')='SUN' THEN 1 ELSE 0 END) +
      (CASE WHEN TO_CHAR(CompleteDate,'DY','nls_date_language=english')='SAT' THEN 1 ELSE 0 END))*SAT_TIME
 
    ELSE ((TRUNC(CompleteDate) - TRUNC(InstallDate) ) +1)*24

    END AS Jan16  

FROM Asset, Jan16;



--$$$$$$$$$$$$$---
With Asset AS (
SELECT 
SQL_142.prv_value ASSET_NAME,
O.OBJ_CODE Equipment,
O.OBJ_VARIABLE3 MF_Hrs_of_Ops,
OBJ_VARIABLE4 SA_Hrs_of_Ops,
OBJ_VARIABLE5 SU_Hrs_of_Ops,

CASE LENGTH(OBJ_VARIABLE4)
  WHEN 4 THEN 'ALL'
  WHEN 1    THEN 'MF'
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE 'MFSS'
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS OP_DAY,

CASE LENGTH(OBJ_VARIABLE3)
  WHEN 4 THEN 24
  WHEN 1    THEN 0
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE Round(to_number(to_char(TO_DATE( substr(OBJ_VARIABLE3,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE3,1,4),'HH24MI')))*24,1)
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS MF_TIME,

CASE LENGTH(OBJ_VARIABLE4)
  WHEN 4 THEN 24
  WHEN 1    THEN 0
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE Round(to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI')))*24,1)
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS SAT_TIME,

CASE LENGTH(OBJ_VARIABLE5)
  WHEN 4 THEN 24
  WHEN 1    THEN 0
  --ELSE to_number(to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE4,1,4),'HH24MI'),'HH24MI'))
  ELSE Round(to_number(to_char(TO_DATE( substr(OBJ_VARIABLE5,-4,4),'HH24MI')- TO_DATE( substr(OBJ_VARIABLE5,1,4),'HH24MI')))*24,1)
  --ELSE to_char(TO_DATE( substr(OBJ_VARIABLE4,-4,4),'HH24MI'),'HH24MI')
END AS SUN_TIME

--OBJ_VARIABLE6 WK_Hrs_of_Ops
FROM r5objects o  , r5propertyvalues SQL_142

WHERE o.obj_obrtype ='A' AND O.OBJ_STATUS <> 'EO' AND O.OBJ_STATUS <> 'RET' AND O.OBJ_STATUS = 'I' AND SQL_142.prv_value IS NOT NULL AND
obj_code||'#'||obj_org=SQL_142.prv_code(+) AND (SQL_142.prv_rentity(+) = 'OBJ') AND (SQL_142.prv_property(+)='ASSETNAM')
and O.OBJ_CLASS = 'MRI'
ORDER BY SQL_142.prv_value),
--##start year calculation here##--

Jan16 AS
  (
     SELECT 
            TO_DATE('01-JAN-16') AS InstallDate,
            TO_DATE('31-JAN-16') AS CompleteDate

       FROM dual
  )

--SELECT ASSET_NAME, Equipment, OP_Day ,MF_TIME, SAT_TIME, SUN_TIME, Jan16 
--FROM Asset, Jan16

SELECT ASSET_NAME, Equipment, OP_DAY, MF_TIME, SAT_TIME, SUN_TIME,
 
  CASE OP_DAY
    WHEN 'MF' THEN 
      (TRUNC(CompleteDate) - TRUNC(InstallDate) ) +1 - 
      ((((TRUNC(CompleteDate,'D'))-(TRUNC(InstallDate,'D')))/7)*2) -
      (CASE WHEN TO_CHAR(InstallDate,'DY','nls_date_language=english')='SUN' THEN 1 ELSE 0 END) -
      (CASE WHEN TO_CHAR(CompleteDate,'DY','nls_date_language=english')='SAT' THEN 1 ELSE 0 END) 
    WHEN 'MFSS' THEN (TRUNC(CompleteDate) - TRUNC(InstallDate) ) +1
 
    ELSE 31

    END AS Jan16  

FROM Asset, Jan16;





select evt_code "WO#", evt_desc Description, evt_object Equipment, evt_mrc Department, evt_status Status,
       evt_reported "Date Reported", evt_completed "Date Completed", evt_downtime "Downtime Hours", add_text Comments
from  r5events LEFT OUTER JOIN r5addetails on ( evt_code = add_code and  'EVNT' = add_rentity )
where evt_rtype in ('PPM', 'JOB') and evt_status <> 'A'
order by evt_reported desc

--***
select * from r5addetails where add_rentity = 'EVNT' order by add_code desc;
--


--update the Station Name
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-013' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-014' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-007' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-006' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-005' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-001' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-002' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-003' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-004' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-010' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-009' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-008' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'FDX-FUJI-011' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'IIP-FUJI-60' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'IIP-FUJI-062' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '(NONE)' WHERE OBJ_CODE = 'SPECT-DIGIRAD-ERGO-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '000P000101' WHERE OBJ_CODE = 'XRAY-PHILIPS-DIAGNOSTOMNI-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '10502200-60225' WHERE OBJ_CODE = 'XRAY-SIEMENS-LUMINOS-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '1064f1' WHERE OBJ_CODE = 'MRI-GE-SIGNA-13' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '1070f2' WHERE OBJ_CODE = 'MRI-GE-SIGNA-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '1109f3' WHERE OBJ_CODE = 'MRI-GE-SIGNA-11' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '1121f4' WHERE OBJ_CODE = 'MRI-GE-SIGNA-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '1135f5' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '9900 OEC C-ARM' WHERE OBJ_CODE = 'CARM-OEC-9800-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = '9900C-ARM' WHERE OBJ_CODE = 'CARM-OEC-9900-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'A5' WHERE OBJ_CODE = 'XRAY-GE-DISCOVER-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ACB21739DEF' WHERE OBJ_CODE = 'XRAY-GE-DEFINIUM-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ACB21739DEF' WHERE OBJ_CODE = 'XRAY-GE-XQI-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ACB71029DEF' WHERE OBJ_CODE = 'XRAY-GE-DEFINIUM-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ACB71051DEF' WHERE OBJ_CODE = 'XRAY-GE-DEFINIUM-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ACBOEC2' WHERE OBJ_CODE = 'CYSTO-OEC-UROVIEW-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ACT5' WHERE OBJ_CODE = 'CT-GE-LS-VCT-64SLICE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA11' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-11' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA12' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-12' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA3' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA6' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA7' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA8' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ALOKA9' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'AMR13' WHERE OBJ_CODE = 'MRI-GE-DISCOVERY-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ARCADISOR20226' WHERE OBJ_CODE = 'CARM-SIEMENS-ARCADIS-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ARCADISVA10085' WHERE OBJ_CODE = 'CARM-SIEMENS-ARCADIS-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ARCADISVA10087' WHERE OBJ_CODE = 'CARM-SIEMENS-ARCADIS-14' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ARTIS147557' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-ZEE-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'AXIS05255' WHERE OBJ_CODE = 'CATH-SIEMENS-ARTISZEE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'AXIS05888' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-ZEE-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'AXIS06170' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-ZEE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'BS003MRC' WHERE OBJ_CODE = 'MRI-SIEMENS-ESPREE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'BSR05092' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-DTA-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'BSR05098' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-DTA-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'BSR05237' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-DTA-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'BSR07366' WHERE OBJ_CODE = 'ANGIO-SIEMENS-ARTIS-DTA-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'bvct' WHERE OBJ_CODE = 'CT-GE-LS-VCT-64SLICE-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CMR1OWO' WHERE OBJ_CODE = 'MRI-GE-DISCOVERY-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT06_OC0' WHERE OBJ_CODE = 'CT-GE-LS-4SLICE-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT07_OC0' WHERE OBJ_CODE = 'CT-GE-LS-4SLICE-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct09' WHERE OBJ_CODE = 'CT-GE-LS-VCT-64SLICE-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct12' WHERE OBJ_CODE = 'CT-GE-LS-VCT-64SLICE-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct2' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct23' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct24' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct27' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ct28' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT49234' WHERE OBJ_CODE = 'CT-SIEMENS-SOMATOM-16SLICE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT4S' WHERE OBJ_CODE = 'CT-SIEMENS-SOMATOM FLASH-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT54043' WHERE OBJ_CODE = 'CT-SIEMENS-SOMATOM-64SLICE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT7' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CT8' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CTAWP66618' WHERE OBJ_CODE = 'CT-SIEMENS-SOMATOM-AS-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CTNAV51952' WHERE OBJ_CODE = 'CT-SIEMENS-16SLICE-ANGIO-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'CX50-1' WHERE OBJ_CODE = 'US-PHILIPS-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'D690' WHERE OBJ_CODE = 'PET-CT-GE-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'd710a' WHERE OBJ_CODE = 'PET-CT-GE-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'd710b' WHERE OBJ_CODE = 'PET-CT-GE-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dc-a1' WHERE OBJ_CODE = 'XRAY-GE-XQI-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dc-a6' WHERE OBJ_CODE = 'XRAY-GE-XQI-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dc-c1' WHERE OBJ_CODE = 'XRAY-GE-XQI-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dc-c2' WHERE OBJ_CODE = 'XRAY-GE-XQI-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dc-dc' WHERE OBJ_CODE = 'XRAY-GE-XQI-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dc-roc' WHERE OBJ_CODE = 'XRAY-GE-XQI-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'MRI-GE-SIGNA-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'MRI-GE-SIGNA-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'MRI-GE-SIGNA-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'MRI-GE-SIGNA-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'GAMCAM-SIEMENS-ECAM2' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'GAMCAM-SIEMENS-ECAM3' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Decommissioned' WHERE OBJ_CODE = 'SPECT-SIEMENS-SYMBIA-S1' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dr-a4' WHERE OBJ_CODE = 'XRAY-GE-XRD-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dr-c3' WHERE OBJ_CODE = 'XRAY-GE-XRD-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'dstealkek' WHERE OBJ_CODE = 'PET-CT-GE-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'EC' WHERE OBJ_CODE = 'XRAY-GE-DISCOVER-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ECFLASHCT' WHERE OBJ_CODE = 'CT-SIEMENS-SOMATOM FLASH-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Eleva' WHERE OBJ_CODE = 'XRAY-PHILIPS-DIAGNOSTOMNI-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'f12' WHERE OBJ_CODE = 'XRAY-GE-XQI-11' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'fcr5000-3' WHERE OBJ_CODE = 'CR-READER-FUJI-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'FLC3655' WHERE OBJ_CODE = 'XRAY-SIEMENS-SIRESKOP-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'FLC3732' WHERE OBJ_CODE = 'XRAY-SIEMENS-SIRESKOP-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'GELOGIQE9-3' WHERE OBJ_CODE = 'US-GE-LOGIQE9-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'GELOGIQE9-4' WHERE OBJ_CODE = 'US-GE-LOGIQE9-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'GENUSICU' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'h4' WHERE OBJ_CODE = 'PET-CT-GE-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'i1' WHERE OBJ_CODE = 'XRAY-GE-XQI-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'I10' WHERE OBJ_CODE = 'XRAY-GE-XQI-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'i5' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'i6' WHERE OBJ_CODE = 'CT-GE-REVOLUTIONGS-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'i7' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'i8' WHERE OBJ_CODE = 'CT-GE-REVOLUTIONGS-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'IU22 1' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 10' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 11' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-16' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 3' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 4' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 5' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 6X' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'iU22 7' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'IU22 9' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'IU22-EC' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LE9103552' WHERE OBJ_CODE = 'US-GE-LOGIQE9-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LE9103915' WHERE OBJ_CODE = 'US-GE-LOGIQE9-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LE9108927' WHERE OBJ_CODE = 'US-GE-LOGIQE9-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LE9110014' WHERE OBJ_CODE = 'US-GE-LOGIQE9-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LOGIQE' WHERE OBJ_CODE = 'US-GE-LOGIQE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LOGIQI' WHERE OBJ_CODE = 'US-GE-LOGICI-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'LOGIQi2' WHERE OBJ_CODE = 'US-GE-LOGICI-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'mCTFlow1' WHERE OBJ_CODE = 'PETCT-SIEMENS-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS1' WHERE OBJ_CODE = 'US-PHILIPS-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS2' WHERE OBJ_CODE = 'US-PHILIPS-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS3' WHERE OBJ_CODE = 'US-PHILIPS-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS4' WHERE OBJ_CODE = 'US-PHILIPS-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS5' WHERE OBJ_CODE = 'US-PHILIPS-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS6' WHERE OBJ_CODE = 'US-PHILIPS-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS7' WHERE OBJ_CODE = 'US-PHILIPS-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS8' WHERE OBJ_CODE = 'US-PHILIPS-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MDACC BRUS9' WHERE OBJ_CODE = 'US-PHILIPS-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Mobile MR3' WHERE OBJ_CODE = 'MRI-GE-SIGNA-15' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR10-AERA' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR11-AERA' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR14OW0' WHERE OBJ_CODE = 'MRI-GE-DISCOVERY-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR15OW0' WHERE OBJ_CODE = 'MRI-GE-18' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR20' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR21' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR22' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MR23' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'MRC30427' WHERE OBJ_CODE = 'MRI-SIEMENS-ESPREE-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'NIRUS10' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'NIRUS4' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'NIRUS5' WHERE OBJ_CODE = 'US-ALOKA-MOBILE-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'NMQDRBMD1' WHERE OBJ_CODE = 'BMD-HOLOGIC-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'NMQDRBMD2' WHERE OBJ_CODE = 'BMD-LORAD-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Not on PACS' WHERE OBJ_CODE = 'CARM-OEC-9800-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Not on PACS' WHERE OBJ_CODE = 'CARM-OEC-9800-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'Not on PACS' WHERE OBJ_CODE = 'US-PHILIPS-MOBILE-12' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'OEC 2800' WHERE OBJ_CODE = 'CYSTO-OEC-UROVIEW-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'OEC 9800' WHERE OBJ_CODE = 'CARM-OEC-9800-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'OECCARM13' WHERE OBJ_CODE = 'CARM-OEC-9900-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'OECCARM5' WHERE OBJ_CODE = 'CARM-OEC-9900-06' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'OECCARM6' WHERE OBJ_CODE = 'CARM-OEC-9900-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'OECCARM7' WHERE OBJ_CODE = 'CARM-OEC-9900-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'REVOLUTION1' WHERE OBJ_CODE = 'XRAY-CARESTREAM-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'REVOLUTION2' WHERE OBJ_CODE = 'XRAY-CARESTREAM-03' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'REVOLUTION3' WHERE OBJ_CODE = 'XRAY-CARESTREAM-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'REVOLUTION4' WHERE OBJ_CODE = 'XRAY-CARESTREAM-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ROCMR1' WHERE OBJ_CODE = 'MRI-GE-15' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ROCMR2' WHERE OBJ_CODE = 'MRI-GE-16' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ROCMR3' WHERE OBJ_CODE = 'MRI-GE-17' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'RoseCTChest' WHERE OBJ_CODE = 'XRAY-GE-DISCOVER-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru103' WHERE OBJ_CODE = 'CR-READER-FUJI-07' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'RU123' WHERE OBJ_CODE = 'CR-READER-FUJI-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru126' WHERE OBJ_CODE = 'CR-READER-FUJI-05' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru134' WHERE OBJ_CODE = 'CR-READER-FUJI-13' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru135' WHERE OBJ_CODE = 'CR-READER-FUJI-14' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru139' WHERE OBJ_CODE = 'CR-READER-FUJI-12' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru144' WHERE OBJ_CODE = 'CR-READER-FUJI-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru179' WHERE OBJ_CODE = 'CR-READER-FUJI-10' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru60' WHERE OBJ_CODE = 'CR-READER-FUJI-15' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru90' WHERE OBJ_CODE = 'CR-READER-FUJI-09' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'ru97' WHERE OBJ_CODE = 'CR-READER-FUJI-11' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SCRB3CT' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAS2' WHERE OBJ_CODE = 'SPECT-SIEMENS-SYMBIA-S2' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAS3' WHERE OBJ_CODE = 'SPECT-SIEMENS-SYMBIA-S3' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAS4' WHERE OBJ_CODE = 'SPECT-SIEMENS-SYMBIA-S4' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAS5' WHERE OBJ_CODE = 'SPECT-SIEMENS-SYMBIA-S5' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT1' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T1' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT2' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T2' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT3' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T3' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT4' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T4' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT6' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T6' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT7' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T7' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'SYMBIAT8' WHERE OBJ_CODE = 'SPECTCT-SIEMENS-SYMBIA-T8' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'VIRLOGIQE9' WHERE OBJ_CODE = 'US-GE-LOGIQE9-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHBMD' WHERE OBJ_CODE = 'BMD-HOLOGIC-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHBRUS1' WHERE OBJ_CODE = 'US-PHILIPS-11' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHBRUS2' WHERE OBJ_CODE = 'US-PHILIPS-12' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHCT1' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-13' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHCT2' WHERE OBJ_CODE = 'CT-GE-DISCOVERY-12' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHGENUS1' WHERE OBJ_CODE = 'US-PHILIPS-13' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHGENUS2' WHERE OBJ_CODE = 'US-PHILIPS-14' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHIC XR656' WHERE OBJ_CODE = 'XRAY-GE-DISCOVERY-04' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHMR1' WHERE OBJ_CODE = 'MRI-SIEMENS-AERA-08' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'WHMR2' WHERE OBJ_CODE = 'MRI-SIEMENS-SKYRA-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'whpet' WHERE OBJ_CODE = 'PETCT-SIEMENS-02' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'XELERIS-QH7F2UO' WHERE OBJ_CODE = 'MBI-GE-01' AND OBJ_OBTYPE = 'A';
UPDATE EAM.R5OBJECTS  SET OBJ_UDFCHAR03 = 'XP10093902-2115' WHERE OBJ_CODE = 'XRAY-SIEMENS-LUMINOS-01' AND OBJ_OBTYPE = 'A';
SELECT * FROM r5events;

SELECT * FROM R5OBJECTS order by OBJ_RECORD desc;

SELECT * FROM R5PROPERTYVALUES WHERE PRV_RENTITY = 'OBJ' order by PRV_CREATED desc;

SELECT * FROM R5PROPERTYVALUES WHERE PRV_RENTITY = 'EVNT' order by PRV_CREATED desc;

-- TEST ON THIS ONE OK ... UPDATE THESE WO 59252, 62134,  ***THIS 2 DOES NOT WORK (CAN'T ADD CUSTOME FIELD) !! 61768, 61573, 

DECLARE
--ADD THE WO NUMBER HERE ABER THE :=
WOCODE R5EVENTS.EVT_CODE%TYPE := '59252';
WOOBJECT R5EVENTS.EVT_OBJECT%TYPE;
TIME_REPORTED EAM.R5EVENTS.EVT_REPORTED%TYPE;

SITE_ID 	R5OBJECTS.OBJ_MANUFACTMODEL%TYPE;
SA_HRS 	R5OBJECTS.OBJ_VARIABLE4%TYPE;
SU_HRS 	R5OBJECTS.OBJ_VARIABLE5%TYPE;
VENDOR 	R5OBJECTS.OBJ_MANUFACT%TYPE;
MODALITY 	R5OBJECTS.OBJ_CLASS%TYPE;
WKHRS 	R5OBJECTS.OBJ_VARIABLE6%TYPE;
MF_HRS 	R5OBJECTS.OBJ_VARIABLE3%TYPE;
CHRSMF 	R5OBJECTS.OBJ_UDFCHAR01%TYPE;
ROOM 			R5PROPERTYVALUES.PRV_VALUE%TYPE;
ANAME 		R5PROPERTYVALUES.PRV_VALUE%TYPE;
OEM 			R5PROPERTYVALUES.PRV_VALUE%TYPE;
DNAME 		R5PROPERTYVALUES.PRV_VALUE%TYPE;
CLINIC_AREA 	R5PROPERTYVALUES.PRV_VALUE%TYPE;
FLOOR1 		R5PROPERTYVALUES.PRV_VALUE%TYPE;

BEGIN
--get the equipment name (EVT_OBJECT) from the R5EVENTS table given WO number
SELECT EVT_REPORTED, EVT_OBJECT INTO TIME_REPORTED, WOOBJECT FROM R5EVENTS WHERE EVT_CODE = WOCODE;
--get the non-custom field values
SELECT OBJ_MANUFACTMODEL, OBJ_VARIABLE4, OBJ_VARIABLE5,  OBJ_MANUFACT, OBJ_CLASS, OBJ_VARIABLE6, OBJ_VARIABLE3, OBJ_UDFCHAR01
	INTO SITE_ID, SA_HRS, SU_HRS, VENDOR, MODALITY, WKHRS, MF_HRS, CHRSMF FROM R5OBJECTS WHERE OBJ_CODE=WOOBJECT;
--get the custom field value
SELECT PRV_VALUE INTO ROOM 		FROM R5PROPERTYVALUES WHERE PRV_CODE=WOOBJECT||'#*' AND PRV_RENTITY='OBJ' AND PRV_PROPERTY='ROOMNAME';
SELECT PRV_VALUE INTO ANAME		FROM R5PROPERTYVALUES WHERE PRV_CODE=WOOBJECT||'#*' AND PRV_RENTITY='OBJ' AND PRV_PROPERTY='ASSETNAM';
SELECT PRV_VALUE INTO OEM			FROM R5PROPERTYVALUES WHERE PRV_CODE=WOOBJECT||'#*' AND PRV_RENTITY='OBJ' AND PRV_PROPERTY='OEM';
SELECT PRV_VALUE INTO DNAME		FROM R5PROPERTYVALUES WHERE PRV_CODE=WOOBJECT||'#*' AND PRV_RENTITY='OBJ' AND PRV_PROPERTY='DOMAIN';
SELECT PRV_VALUE INTO CLINIC_AREA	FROM R5PROPERTYVALUES WHERE PRV_CODE=WOOBJECT||'#*' AND PRV_RENTITY='OBJ' AND PRV_PROPERTY='CLINIC';
SELECT PRV_VALUE INTO FLOOR1		FROM R5PROPERTYVALUES WHERE PRV_CODE=WOOBJECT||'#*' AND PRV_RENTITY='OBJ' AND PRV_PROPERTY='FLOOR';

IF 
SITE_ID  		IS NOT NULL AND SA_HRS	IS NOT NULL AND SU_HRS  		IS NOT NULL AND VENDOR	IS NOT NULL AND MODALITY	IS NOT NULL 
AND WKHRS   	IS NOT NULL AND MF_HRS  	IS NOT NULL AND CHRSMF      	IS NOT NULL AND ROOM      	IS NOT NULL AND ANAME 	IS NOT NULL 
AND OEM     	IS NOT NULL AND DNAME   	IS NOT NULL AND CLINIC_AREA 	IS NOT NULL AND FLOOR1    	IS NOT NULL 
THEN
--DBMS_OUTPUT.PUT_LINE ( SITE_ID||'   ' || TIME_REPORTED ||'   ' ||  SA_HRS||'   ' || SU_HRS||'   ' || VENDOR||'   ' || MODALITY||'   ' || WKHRS||'   ' || MF_HRS||'   ' || CHRSMF||'   ' || ROOM||'   ' || ANAME||'   ' || OEM||'   ' || DNAME||'   ' || CLINIC_AREA||'   ' || FLOOR1  );

  INSERT ALL 
INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('SITEID','EVNT','*',WOCODE,1,SITE_ID,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('SAHRS','EVNT','*',WOCODE,1,SA_HRS,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('SUHRS','EVNT','*',WOCODE,1,SU_HRS,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('VENDOR','EVNT','*',WOCODE,1,VENDOR,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('MODALITY','EVNT','*',WOCODE,1,MODALITY,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('WKHRS','EVNT','*',WOCODE,1,WKHRS,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('MFHRS','EVNT','*',WOCODE,1,MF_HRS,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('CHRSMF','EVNT','*',WOCODE,1,CHRSMF,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('ROOM','EVNT','*',WOCODE,1,ROOM,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('ASSETNAM','EVNT','*',WOCODE,1,ANAME,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('OEM','EVNT','*',WOCODE,1,OEM,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('DOMAIN','EVNT','*',WOCODE,1,DNAME,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('CLINIC','EVNT','*',WOCODE,1,CLINIC_AREA,null,null,'*',0,time_reported,time_reported,'-')

INTO EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('FLOOR','EVNT','*',WOCODE,1,FLOOR1,null,null,'*',0,time_reported,time_reported,'-')

SELECT 1 FROM DUAL;

END IF;
EXCEPTION
WHEN OTHERS THEN NULL;
END;


--*********************************

SELECT 
O.OBJ_CODE Equipment,
O.OBJ_CODE,
SQL_142.prv_value ASSET_NAME,
obj_manufactmodel SiteID,
o.obj_class Modality,
o.obj_manufact Service_Vendor,
SQL_160.prv_value OEM,
SQL_147.prv_value DOMAIN,
SQL_161.prv_value CLINIC_AREA,
SQL_163.prv_value FLOOR,
SQL_139.prv_value ROMENAME,
O.OBJ_VARIABLE3 MF_Hrs_of_Ops,
OBJ_VARIABLE4 SA_Hrs_of_Ops,
OBJ_VARIABLE5 SU_Hrs_of_Ops,
OBJ_VARIABLE6 WK_Hrs_of_Ops,
OBJ_UDFCHAR01 C_Hrs_MF
FROM r5objects o, 
r5propertyvalues SQL_139, r5propertyvalues SQL_147, r5propertyvalues SQL_142, r5propertyvalues SQL_160, r5propertyvalues SQL_161, r5propertyvalues SQL_163
WHERE
obj_code||'#'||obj_org=SQL_147.prv_code(+) and (SQL_147.prv_rentity(+) = 'OBJ') and (SQL_147.prv_property(+)='DOMAIN') and 
obj_code||'#'||obj_org=SQL_139.prv_code(+) and (SQL_139.prv_rentity(+) = 'OBJ') and (SQL_139.prv_property(+)='ROOMNAME') and 
obj_code||'#'||obj_org=SQL_160.prv_code(+) and (SQL_160.prv_rentity(+) = 'OBJ') and (SQL_160.prv_property(+)='OEM') and 
obj_code||'#'||obj_org=SQL_142.prv_code(+) and (SQL_142.prv_rentity(+) = 'OBJ') and (SQL_142.prv_property(+)='ASSETNAM') and
obj_code||'#'||obj_org=SQL_161.prv_code(+) and (SQL_161.prv_rentity(+) = 'OBJ') and (SQL_161.prv_property(+)='CLINIC') and 
obj_code||'#'||obj_org=SQL_163.prv_code(+) and (SQL_163.prv_rentity(+) = 'OBJ') and (SQL_163.prv_property(+)='FLOOR') AND
OBJ_CODE IN (SELECT EVT_OBJECT FROM R5EVENTS WHERE EVT_RTYPE IN ( 'JOB', 'PPM') AND (EVT_CODE = 59252 OR EVT_CODE = 62134))
;


--vIEW CUSTOM VALUE FROM ASSETE ... IN THIS CASE EPOWER
SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_RENTITY = 'OBJ' AND PRV_PROPERTY = 'EPOWER';

--


to move 

--**to move serei at t atime. 
seriesID, number of Image, and movedSeries
from 
SereisInstanceUid = 9,222

Jforster@mdanderson.org, Robert.Modglin@mdanderson.org, Douglas.Webb@mdanderson.org, rafael.diaz@mdanderson.org, Kelly.Greer@mdanderson.org, AReyes7@mdanderson.org

TD56-A781-A650-10FC-3304

--SELECT WO with 2 SITE ID from Assets and from WO custom
select 
e.evt_code WO,
O.OBJ_MANUFACTMODEL Site_ID,
SQL_115.prv_value SITE_ID_EVT,
EVT_REPORTED Date_Reported,
EVT_TARGET TARGET,
r5o7.o7get_desc('EN','UCOD', e.evt_status,'EVST', '') WO_STATUS, 
EVT_MRC Building,
O.OBJ_CODE,
O.OBJ_COSTCODE Cost_Center, 
O.OBJ_CLASS Modality,
SQL_41.prv_value Modality_WO,
SQL_65.PRV_VALUE VEN_Total_Labor_Hrs,
--down time 
E.EVT_DOWNTIMEHRS System_Hard_Down_Hrs_Ops,
--planned or unplanned
SQL_51.prv_value WO_Type, 
--pm or and stuff
r5o7.o7get_desc('EN','UCOD', e.evt_jobtype,'JBTP', '') Event,
--wo asset name
SQL_48.prv_value Asset_Name, 
--asset name from object
SQL_49.prv_value AssetName,
r5o7.o7get_desc('EN','UCOD', o.obj_status,'OBST', '') Asset_Status
from r5events e, r5activities a, r5objects o, r5addetails ad,
   r5propertyvalues SQL_41, r5propertyvalues SQL_51, r5propertyvalues SQL_65, r5propertyvalues SQL_49, r5propertyvalues SQL_48, r5propertyvalues SQL_115

where
e.evt_rstatus IN ('Q', 'R', 'C') 
AND        e.evt_rtype IN ('JOB', 'PPM')
 
AND e.evt_code = a.act_event (+)
AND e.evt_object = o.obj_code(+)
AND e.evt_object_org = o.obj_org(+)
AND       (a.act_act is null or a.act_act=(select min(b.act_act) from r5activities b where b.act_event=a.act_event) )
   
AND AD.ADD_LINE(+) = A.act_act AND a.act_event || '#10' = AD.ADD_CODE(+)
          AND E.EVT_STATUS <> 'A'
          AND E.EVT_STATUS <> 'REJ'              
          AND E.EVT_STATUS <> 'RJDD'

and evt_code=SQL_41.prv_code(+) and  (SQL_41.prv_rentity(+) = 'EVNT') and (SQL_41.prv_property(+)='MODALITY')
and (evt_code=SQL_48.prv_code(+) and SQL_48.prv_rentity(+) = 'EVNT') and (SQL_48.prv_property(+)='ASSETNAM')
and obj_code||'#'||obj_org=SQL_49.prv_code(+) and (SQL_49.prv_rentity(+) = 'OBJ') and (SQL_49.prv_property(+)='ASSETNAM')

and evt_code=SQL_51.prv_code(+) and (SQL_51.prv_rentity(+) = 'EVNT') and (SQL_51.prv_property(+)='WOTYPE')
and evt_code=SQL_65.prv_code(+) and (SQL_65.prv_rentity(+) = 'EVNT') and (SQL_65.prv_property(+)='SVCHRS')
and evt_code=SQL_115.prv_code(+) and (SQL_65.prv_rentity(+) = 'EVNT') and (SQL_115.prv_property(+)='SITEID')
--modality is 'MRI'
--check for CT4, CT_I6 or CT-I8
--and SQL_49.prv_value = 'CT-I8'
and OBJ_CODE = 'CT-GE-LS-16SLICE-1'
--and O.OBJ_CODE = 'CT-GE-LS-16SLICE-1'
--and O.OBJ_CLASS = 'MRI'
--event_report alway has value null = empty
--and EVT_REPORTED is null
--group by SQL_49.prv_value
--and r5o7.o7get_desc('EN','UCOD', o.obj_status,'OBST', '') != 'Retired'
--AND (trunc(EVT_REPORTED) >= TO_DATE('14-NOV-01', 'YY-MON-DD') AND trunc(EVT_REPORTED) <= TO_DATE('15-OCT-31', 'YY-MON-DD'))
order by e.evt_code desc
--order by SQL_49.prv_value desc
;

-- Update costum Field from R5PROPERTYVALUES
--READ STATEMENT
SELECT PRV_PROPERTY, PRV_CODE, PRV_VALUE FROM EAM.R5PROPERTYVALUES
WHERE PRV_CODE = '50610' AND PRV_PROPERTY = 'VENDOR';

SELECT * FROM EAM.R5PROPERTYVALUES
WHERE PRV_CODE = '50610' AND PRV_PROPERTY = 'VENDOR';
-- update statement
UPDATE EAM.R5PROPERTYVALUES
SET PRV_VALUE = 'GE'
WHERE PRV_CODE = '50610' AND PRV_PROPERTY = 'VENDOR';

Joe report
SELECT O.OBJ_COSTCODE, O.OBJ_LOCATION, O.OBJ_MANUFACTMODEL, O.OBJ_DESC, O.OBJ_CLASS, O.OBJ_VARIABLE1, O.OBJ_SERIALNO, O.OBJ_VARIABLE2, O.OBJ_CODE
FROM EAM.R5OBJECTS O
WHERE OBJ_OBTYPE = 'A' AND O.OBJ_CLASS = 'MRI' AND O.OBJ_COSTCODE = 'MRI' OR O.OBJ_CLASS = 'MRI';

SELECT
O.OBJ_CODE Equipment,
SQL_142.prv_value ASSET_NAME
from r5objects o  
Join r5propertyvalues SQL_142 ON EVT.EVT_OBJECT = OBJ.OBJ_CODE
where o.obj_obrtype ='A' and O.OBJ_STATUS <> 'EO' and O.OBJ_STATUS <> 'RET' and
o.obj_code||'#'||o.obj_org=SQL_142.prv_code(+) and (SQL_142.prv_rentity(+) = 'OBJ') and (SQL_142.prv_property(+)='ASSETNAM');

--from Peter:
SELECT OBJ_CODE, SUM(EVT_DOWNTIMEHRS), OBJ_VARIABLE6 * 4 AS TOTAL_MONTHLY_HRS 
FROM EAM.R5EVENTS EVT 
JOIN EAM.R5OBJECTS OBJ ON EVT.EVT_OBJECT = OBJ.OBJ_CODE 
WHERE OBJ_OBTYPE = 'A' 
AND OBJ_STATUS = 'I'
AND EVT_DATE >= '14-NOV-01'
AND EVT_DATE <= '15-OCT-31'
GROUP BY OBJ_CODE, OBJ_VARIABLE6


SELECT  A.EVT_CODE FROM EAM.R5EVENTS A WHERE A.EVT_CODE NOT IN (
SELECT A.EVT_CODE FROM EAM.R5EVENTS A
JOIN EAM.R5PROPERTYVALUES B
ON A.EVT_CODE = B.PRV_CODE
WHERE EVT_COSTCODE = 'WHIC'
AND B.PRV_PROPERTY = 'WKHRS')
AND A.EVT_COSTCODE = 'WHIC'
ORDER BY A.EVT_CODE DESC;
********************** this one work******
DECLARE
  --i NUMBER := 1;
  workorder EAM.R5EVENTS.EVT_CODE%TYPE;
  time_reported EAM.R5EVENTS.EVT_DATE%TYPE;
BEGIN
  FOR item IN (
       SELECT  A.EVT_CODE FROM EAM.R5EVENTS A WHERE A.EVT_CODE NOT IN (
	SELECT A.EVT_CODE FROM EAM.R5EVENTS A
	JOIN EAM.R5PROPERTYVALUES B
	ON A.EVT_CODE = B.PRV_CODE
	WHERE EVT_COSTCODE = 'WHIC'
	AND B.PRV_PROPERTY = 'WKHRS')
	AND A.EVT_COSTCODE = 'WHIC'
	ORDER BY A.EVT_CODE DESC
  ) 
  LOOP
  --DBMS_OUTPUT.PUT_LINE ('item: ' || i || ':  ' || item.EVT_CODE);
  SELECT EVT_DATE, EVT_CODE INTO time_reported, workorder FROM EAM.R5EVENTS WHERE EVT_CODE = item.EVT_CODE;
  --DBMS_OUTPUT.PUT_LINE (time_reported);
  --DBMS_OUTPUT.PUT_LINE (workorder ||'  ' ||time_reported);
  Insert into EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('WKHRS','EVNT','*',workorder,1,'60',null,null,'*',0,time_reported,time_reported,'-');
  --i:= i+1;
  END LOOP;
END;

************* i used this ****
DECLARE
  --i NUMBER := 1;
  workorder EAM.R5EVENTS.EVT_CODE%TYPE;
  time_reported EAM.R5EVENTS.EVT_DATE%TYPE;
BEGIN
  FOR item IN (
  SELECT  A.EVT_CODE FROM EAM.R5EVENTS A WHERE A.EVT_CODE NOT IN (
	SELECT A.EVT_CODE FROM EAM.R5EVENTS A
	JOIN EAM.R5PROPERTYVALUES B
	ON A.EVT_CODE = B.PRV_CODE
	WHERE EVT_COSTCODE = 'WHIC'
	AND B.PRV_PROPERTY = 'WKHRS')
	AND A.EVT_COSTCODE = 'WHIC'
	ORDER BY A.EVT_CODE DESC
  ) 
  LOOP
  --DBMS_OUTPUT.PUT_LINE ('item: ' || i || ':  ' || item.EVT_CODE);
  SELECT EVT_DATE, EVT_CODE INTO time_reported, workorder FROM EAM.R5EVENTS WHERE EVT_CODE = item.EVT_CODE;
  --DBMS_OUTPUT.PUT_LINE (time_reported);
  --DBMS_OUTPUT.PUT_LINE (workorder ||'  ' ||time_reported);
  Insert into EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('WKHRS','EVNT','*',workorder,1,'60',null,null,'*',0,time_reported,time_reported,'-');
  --i:= i+1;
  END LOOP;
END;

*****************************************

************* i used this FOR eUPDATE ****
DECLARE
  --i NUMBER := 1;
  workorder EAM.R5EVENTS.EVT_CODE%TYPE;
  eupdate EAM.R5PROPERTYVALUES.PRV_DVALUE%TYPE;
BEGIN
  FOR item IN (
		SELECT  P.PRV_CODE, P.PRV_DVALUE
		FROM EAM.R5PROPERTYVALUES P
		JOIN EAM.R5EVENTS EVT
		ON P.PRV_CODE = EVT.EVT_CODE AND P.PRV_PROPERTY = 'EUPDATE' AND P.PRV_DVALUE IS NOT NULL AND TO_CHAR(P.prv_dvalue, 'hh24:mi') != '00:00' AND P.prv_dvalue != EVT.EVT_REPORTED AND EVT.EVT_JOBTYPE = 'UPGRADE'
		ORDER BY PRV_DVALUE DESC
  ) 
  LOOP
  --DBMS_OUTPUT.PUT_LINE ('item: ' || i || ':  ' || item.EVT_CODE);
  SELECT EVT_CODE INTO workorder FROM EAM.R5EVENTS WHERE EVT_CODE = item.PRV_CODE;
  SELECT PRV_DVALUE INTO eupdate FROM EAM.R5PROPERTYVALUES WHERE PRV_CODE = item.PRV_CODE AND PRV_PROPERTY = 'EUPDATE';
  --DBMS_OUTPUT.PUT_LINE (time_reported);
  DBMS_OUTPUT.PUT_LINE ('WO are:  ' ||workorder ||'  eupdate = ' || TO_CHAR(eupdate, 'yyyy/mm/dd hh24:mi') );
  --DBMS_OUTPUT.PUT_LINE (workorder ||'  ' ||time_reported);
  UPDATE EAM.R5EVENTS
  SET EVT_REPORTED = eupdate
  WHERE EVT_CODE = workorder
  --i:= i+1;
  END LOOP;
END;

**********FROM SCHOOL*****
DECLARE
  --i NUMBER := 1;
  workorder EAM.R5EVENTS.EVT_CODE%TYPE;
  eupdate EAM.R5PROPERTYVALUES.PRV_DVALUE%TYPE;
BEGIN
  FOR item IN (
		SELECT  P.PRV_CODE, P.PRV_DVALUE
		FROM EAM.R5PROPERTYVALUES P
		JOIN EAM.R5EVENTS EVT
		ON P.PRV_CODE = EVT.EVT_CODE AND P.PRV_PROPERTY = 'EUPDATE' AND P.PRV_DVALUE IS NOT NULL AND TO_CHAR(P.prv_dvalue, 'hh24:mi') != '00:00' AND P.prv_dvalue != EVT.EVT_REPORTED AND EVT.EVT_JOBTYPE = 'FMI'
		ORDER BY PRV_DVALUE DESC
  ) 
  LOOP
  --DBMS_OUTPUT.PUT_LINE ('item: ' || i || ':  ' || item.EVT_CODE);
  SELECT EVT_CODE INTO workorder FROM EAM.R5EVENTS WHERE EVT_CODE = item.PRV_CODE;
  SELECT PRV_DVALUE INTO eupdate FROM EAM.R5PROPERTYVALUES WHERE PRV_CODE = item.PRV_CODE AND PRV_PROPERTY = 'EUPDATE';
  --DBMS_OUTPUT.PUT_LINE (time_reported);
  --DBMS_OUTPUT.PUT_LINE ('WO are:  ' ||workorder ||'  eupdate = ' || TO_CHAR(eupdate, 'yyyy/mm/dd hh24:mi') );
  --DBMS_OUTPUT.PUT_LINE (workorder ||'  ' ||time_reported);
  UPDATE EAM.R5EVENTS
  SET EVT_REPORTED = eupdate
  WHERE EVT_CODE = workorder;
  --i:= i+1;
  END LOOP;
END;

**************************
DECLARE
--r5events.evt_code%type;
--thomas_wos SYS_REFCURSOR;

CURSOR thomas_wos IS
SELECT  A.EVT_CODE FROM EAM.R5EVENTS A WHERE A.EVT_CODE NOT IN (
SELECT A.EVT_CODE FROM EAM.R5EVENTS A
JOIN EAM.R5PROPERTYVALUES B
ON A.EVT_CODE = B.PRV_CODE
WHERE EVT_MRC = 'WHIC'
AND B.PRV_PROPERTY = 'WKHRS')
AND A.EVT_MRC = 'WHIC'
ORDER BY A.EVT_CODE DESC;
workorders_row thomas_wos%ROWTYPE;
workorder EAM.R5EVENTS.EVT_CODE%TYPE;
--time_reported EAM.R5EVENTS.EVT_REPORTED%TYPE;
BEGIN
  OPEN thomas_wos;
  SELECT * FROM thomas_wos;
  /*
  LOOP
    FETCH thomas_wos INTO workorders_row;
    EXIT WHEN thomas_wos%NOTFOUND; 
    --get workorder and time for each row
    SELECT workorders_row.EVT_CODE, workorders_row.EVT_DATE INTO workorder, time_reported FROM workorders_row;
    --SELECT EAM.R5EVENTS.EVT_REPORTED INTO time_reported FROM EAM.R5EVENTS WHERE EAM.R5EVENTS.EVT_CODE = workorder;
    DBMS_OUTPUT.PUT_LINE (workorder ||'  ' ||time_reported);
    --DBMS_OUTPUT.PUT_LINE (time_reported);
    --Insert into EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
    --values ('WKHRS','EVNT','*',workorder,1,'60',null,null,'*',0,time_reported,time_reported,'-');
  END LOOP;
  */
  CLOSE thomas_wos;
  
END;

--select WO in R5events that are WHIC and has WKHRS in r5property  (the idea is to exclude these type of wo)
SELECT A.EVT_CODE FROM EAM.R5EVENTS A
JOIN EAM.R5PROPERTYVALUES B
ON A.EVT_CODE = B.PRV_CODE
WHERE EVT_MRC = 'WHIC'
AND B.PRV_PROPERTY = 'WKHRS';

DECLARE
--r5events.evt_code%type;
workorder EAM.R5EVENTS.EVT_CODE%TYPE;
time_reported EAM.R5EVENTS.EVT_REPORTED%TYPE;
BEGIN
  workorder := '60777';
  --workorder := '60888';
  --get the report date
  SELECT EVT_REPORTED INTO time_reported FROM EAM.R5EVENTS WHERE EVT_CODE = workorder;
  DBMS_OUTPUT.PUT_LINE (workorder ||'  ' ||time_reported);
  --DBMS_OUTPUT.PUT_LINE (time_reported);
  Insert into EAM.R5PROPERTYVALUES  (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_CREATED,PRV_UPDATED,PRV_NOTUSED) 
  values ('WKHRS','EVNT','*',workorder,1,'60',null,null,'*',0,time_reported,time_reported,'-');
END;



Insert into "EAM"."R5PROPERTYVALUES" (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_NOTUSED) values ('TEST2','EVNT','*','60695',1,null,null,'*',0,'-');

Insert into "EAM"."R5PROPERTYVALUES" (PRV_PROPERTY,PRV_RENTITY,PRV_CLASS,PRV_CODE,PRV_SEQNO,PRV_VALUE,PRV_NVALUE,PRV_DVALUE,PRV_CLASS_ORG,PRV_UPDATECOUNT,PRV_NOTUSED) values ('TEST1','EVNT','*','60695',1,null,null,to_date('09-NOV-15','DD-MON-RR'),'*',0,'-');


INSERT INTO EAM.R5PROPERTYVALUES (PRV_PROPERTY, PRV_RENTITY, PRV_CLASS, PRV_CODE, PRV_SEQNO, PRV_VALUE, PRV_NVALUE, PRV_DVALUE, PRV_CLASS_ORG, PRV_UPDATECOUNT, PRV_CREATED, PRV_UPDATED, PRV_NOTUSED) VALUES ('WKHRS', 'EVNT', '*', 'xxxWOxxx',1, '60', NULL, NULL,'*',0,'xxxDATExx','xxxDATExx','-')
WHERE EAM.R5PROPERTYVALUES.PRV_CODE =

--Display West Houston building WHIC ..
SELECT * FROM EAM.R5EVENTS WHERE EVT_MRC = 'WHIC' ORDER BY EVT_CODE DESC;

--there is an tytp from Yuliya that SEPTEMBE   instead of SEPTEMBER .. see if  this can be fixed from query (not report)
SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_PROPERTY = 'SEPTEMBE' ORDER BY PRV_CREATED;

--select  all the custom fields for particular WO
SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_CODE = '60723' ORDER BY PRV_PROPERTY;

--SELECT PROPERTY OF WOs OR ASSETS
SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_RENTITY = 'EVNT' ORDER BY PRV_CREATED DESC;
SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_RENTITY = 'EVNT' AND PRV_PROPERTY = 'EUPDATE'  ORDER BY PRV_CREATED DESC;
SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_RENTITY = 'OBJ' ORDER BY PRV_CREATED DESC;

SELECT * FROM EAM.R5PROPERTYVALUES WHERE PRV_CODE = '60723' ORDER BY PRV_PROPERTY;

SELECT prv_property, prv_code, TO_CHAR(prv_dvalue, 'yyyy/mm/dd hh:mm'), TO_CHAR(prv_created, 'yyyy/mm/dd hh:mm'), TO_CHAR(prv_updated, 'yyyy/mm/dd hh:mm')  
FROM EAM.R5PROPERTYVALUES 
WHERE PRV_PROPERTY = 'EUPDATE' 
ORDER BY PRV_PROPERTY DESC;

--select for eupdate TASK 12/10/2015 
--FOR  VENT = PM   1283 ROWS
SELECT P.prv_property, P.prv_code, EVT.EVT_JOBTYPE, TO_CHAR(P.prv_dvalue, 'yyyy/mm/dd hh24:mi') PRV_DVALUE, TO_CHAR(P.prv_created, 'yyyy/mm/dd hh:mi') PRV_CREATED, TO_CHAR(P.prv_updated, 'yyyy/mm/dd hh:mi') PRV_UPDATED,  
TO_CHAR(EVT.EVT_REPORTED, 'yyyy/mm/dd hh24:mi') EVT_REPORTED, TO_CHAR(EVT.EVT_DATE, 'yyyy/mm/dd hh24:mi') EVT_DATE, 
EVT.EVT_TYPE, EVT.EVT_DESC, P.prv_code, TO_CHAR(P.prv_dvalue, 'hh24:mi') PRV_DVALUE_HHss
FROM EAM.R5PROPERTYVALUES P
JOIN EAM.R5EVENTS EVT
ON P.PRV_CODE = EVT.EVT_CODE AND P.PRV_PROPERTY = 'EUPDATE' AND P.PRV_DVALUE IS NOT NULL AND TO_CHAR(P.prv_dvalue, 'hh24:mi') != '00:00' AND P.prv_dvalue != EVT.EVT_REPORTED AND EVT.EVT_JOBTYPE = 'PM'
ORDER BY PRV_DVALUE DESC;

--FOR EVENT = FMI   286  ROWS
SELECT P.prv_property, P.prv_code, EVT.EVT_JOBTYPE, TO_CHAR(P.prv_dvalue, 'yyyy/mm/dd hh24:mi') PRV_DVALUE, TO_CHAR(P.prv_created, 'yyyy/mm/dd hh:mi') PRV_CREATED, TO_CHAR(P.prv_updated, 'yyyy/mm/dd hh:mi') PRV_UPDATED,  
TO_CHAR(EVT.EVT_REPORTED, 'yyyy/mm/dd hh24:mi') EVT_REPORTED, TO_CHAR(EVT.EVT_DATE, 'yyyy/mm/dd hh24:mi') EVT_DATE, 
EVT.EVT_TYPE, EVT.EVT_DESC, P.prv_code, TO_CHAR(P.prv_dvalue, 'hh24:mi') PRV_DVALUE_HHss
FROM EAM.R5PROPERTYVALUES P
JOIN EAM.R5EVENTS EVT
ON P.PRV_CODE = EVT.EVT_CODE AND P.PRV_PROPERTY = 'EUPDATE' AND P.PRV_DVALUE IS NOT NULL AND TO_CHAR(P.prv_dvalue, 'hh24:mi') != '00:00' AND P.prv_dvalue != EVT.EVT_REPORTED AND EVT.EVT_JOBTYPE = 'FMI'
ORDER BY PRV_DVALUE DESC;

--FOR EVENT = UPGRADE   22 ROWS
SELECT P.prv_property, P.prv_code, EVT.EVT_JOBTYPE, TO_CHAR(P.prv_dvalue, 'yyyy/mm/dd hh24:mi') PRV_DVALUE, TO_CHAR(P.prv_created, 'yyyy/mm/dd hh:mi') PRV_CREATED, TO_CHAR(P.prv_updated, 'yyyy/mm/dd hh:mi') PRV_UPDATED,  
TO_CHAR(EVT.EVT_REPORTED, 'yyyy/mm/dd hh24:mi') EVT_REPORTED, TO_CHAR(EVT.EVT_DATE, 'yyyy/mm/dd hh24:mi') EVT_DATE, 
EVT.EVT_TYPE, EVT.EVT_DESC, P.prv_code, TO_CHAR(P.prv_dvalue, 'hh24:mi') PRV_DVALUE_HHss
FROM EAM.R5PROPERTYVALUES P
JOIN EAM.R5EVENTS EVT
ON P.PRV_CODE = EVT.EVT_CODE AND P.PRV_PROPERTY = 'EUPDATE' AND P.PRV_DVALUE IS NOT NULL AND TO_CHAR(P.prv_dvalue, 'hh24:mi') != '00:00' AND P.prv_dvalue != EVT.EVT_REPORTED AND EVT.EVT_JOBTYPE = 'UPGRADE'
ORDER BY PRV_DVALUE DESC;
-- update statement
UPDATE EAM.R5PROPERTYVALUES
SET PRV_VALUE = '50'
WHERE PRV_CODE = '56778' AND PRV_PROPERTY = 'WKHRS'

--check
SELECT PRV_VALUE FROM EAM.R5PROPERTYVALUES WHERE PRV_CODE = '56778' AND PRV_PROPERTY = 'WKHRS'



SELECT  COUNT(*) FROM EAM.R5EVENTS A WHERE A.EVT_CODE NOT IN (
SELECT A.EVT_CODE FROM EAM.R5EVENTS A
JOIN EAM.R5PROPERTYVALUES B
ON A.EVT_CODE = B.PRV_CODE
WHERE EVT_MRC = 'WHIC'
AND B.PRV_PROPERTY = 'WKHRS');


SELECT  A.EVT_CODE FROM EAM.R5EVENTS A WHERE A.EVT_CODE NOT IN (
SELECT A.EVT_CODE FROM EAM.R5EVENTS A
JOIN EAM.R5PROPERTYVALUES B
ON A.EVT_CODE = B.PRV_CODE
WHERE EVT_MRC = 'WHIC'
AND B.PRV_PROPERTY = 'WKHRS')
AND A.EVT_MRC = 'WHIC'
ORDER BY A.EVT_CODE DESC;


-- adding the R5EVENT table and insert its data
 CREATE TABLE "EAM"."R5EVENTS" 
   (	"EVT_CODE" VARCHAR2(30 BYTE), 
	"EVT_DESC" VARCHAR2(80 BYTE), 
	"EVT_DATE" DATE, 
	"EVT_MRC" VARCHAR2(15 BYTE), 
  "EVT_REPORTED" DATE, 
  "EVT_CREATED" DATE);
  
  
  Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60695','Scanner Acquisition Failure',to_date('09-NOV-15','DD-MON-RR'),'WHIC',to_date('09-NOV-15','DD-MON-RR'),to_date('09-NOV-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60655','Gradient Amp switched off when running AX T1 of T-spine',to_date('04-NOV-15','DD-MON-RR'),'WHIC',to_date('04-NOV-15','DD-MON-RR'),to_date('04-NOV-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60651','PM',to_date('04-NOV-15','DD-MON-RR'),'WHIC',null,to_date('04-NOV-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60598','System switched off by scanner',to_date('29-OCT-15','DD-MON-RR'),'WHIC',to_date('29-OCT-15','DD-MON-RR'),to_date('29-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60583','PM',to_date('28-OCT-15','DD-MON-RR'),'WHIC',null,to_date('28-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60580','QC during artifact detection test giving error mAs too low',to_date('28-OCT-15','DD-MON-RR'),'WHIC',to_date('28-OCT-15','DD-MON-RR'),to_date('28-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60505','FMi Siemens MR049_14_P Thread UI',to_date('20-OCT-15','DD-MON-RR'),'WHIC',to_date('20-OCT-15','DD-MON-RR'),to_date('20-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60504','FMi Siemens MR049_14_P Thread UI',to_date('20-OCT-15','DD-MON-RR'),'WHIC',to_date('20-OCT-15','DD-MON-RR'),to_date('20-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60476','PM',to_date('16-OCT-15','DD-MON-RR'),'WHIC',null,to_date('16-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60425','BCM unit’s screen tilting over due to loose screw',to_date('12-OCT-15','DD-MON-RR'),'WHIC',to_date('12-OCT-15','DD-MON-RR'),to_date('12-OCT-15','DD-MON-RR'));
Insert into R5EVENTS (EVT_CODE,EVT_DESC,EVT_DATE,EVT_MRC,EVT_REPORTED,EVT_CREATED) values ('60416','Mouse and track ball is not working properly ',to_date('09-OCT-15','DD-MON-RR'),'WHIC',to_date('09-OCT-15','DD-MON-RR'),to_date('09-OCT-15','DD-MON-RR'));

